import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";
const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-ts","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json"),L="galerina-core-compiler/src/leak-proof.ts",X="galerina-core-compiler/src/lexer.ts",C="galerina-core-compiler/src/lint-checker.ts",H="galerina-core-compiler/src/lmanifest-hybrid-verifier.ts",P="galerina-core-compiler/src/lowering-plan.ts",M="galerina-core-compiler/src/manifest-generator.ts";
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)])),RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const RAW=Object.freeze([
  ["leak-proof-test-suite-digest",L,"export function testSuiteDigest("],["leak-proof-build-test-witness",L,"export function buildTestWitness("],["leak-proof-canonical-test-witness",L,"export function canonicalTestWitness("],["leak-proof-canonical-test-witness-leak",L,"function canonicalTestWitness_leak("],["leak-proof-test-witness-digest",L,"export function testWitnessDigest("],["leak-proof-witness-vouches-clean",L,"export function witnessVouchesClean("],
  ["lexer-lex",X,"export function lex("],["lexer-peek",X,"function peek(offset = 0): string"],["lexer-advance",X,"function advance(): string"],["lexer-tok",X,"function tok("],["lexer-diag",X,"function diag("],["lexer-is-ident-start",X,"function isIdentStart("],["lexer-is-ident-continue",X,"function isIdentContinue("],
  ["lint-max-nesting-depth",C,"function maxNestingDepth("],["lint-count-err-propagations",C,"function countErrPropagations("],["lint-check-lint",C,"export function checkLint("],["lint-binding-name-of",C,"function bindingNameOf("],["lint-collect-bindings",C,"function collectBindings("],["lint-collect-reads",C,"function collectReads("],["lint-check-unused-bindings",C,"export function checkUnusedBindings("],
  ["lmanifest-resolve-governance-file",H,"function resolveGovernanceFile("],["lmanifest-make-hybrid-verifier",H,"export function makeLmanifestHybridVerifier("],
  ["lowering-build-typed-array-plan",P,"export function buildTypedArrayLoweringPlan("],["lowering-build-monomorphisation-plan",P,"export function buildMonomorphisationPlan("],["lowering-build-kernel-fusion-plan",P,"export function buildKernelFusionPlan("],["lowering-build-lazy-iterator-chain",P,"export function buildLazyIteratorChain("],
  ["manifest-resolve-compiler-version",M,"export function resolveCompilerVersion("],["manifest-canonical-json",M,"export function canonicalJson("],["manifest-canonical-json-string",M,"function canonicalJsonString("],["manifest-signing-input",M,"export function manifestSigningInput("],["manifest-sig-canon",M,"export function manifestSigCanon("],["manifest-encode-cbor",M,"export function encodeCBOR("],["manifest-cbor-encode-map",M,"function cborEncodeMap("],["manifest-cbor-encode-int",M,"function cborEncodeInt("],["manifest-cbor-encode-text",M,"function cborEncodeText("],["manifest-cbor-encode-bytes",M,"function cborEncodeBytes("],["manifest-cbor-encode-head",M,"function cborEncodeHead("],["manifest-concat-bytes",M,"function concatBytes("],["manifest-decode-cbor",M,"export function decodeCBOR("],["manifest-decode-cbor-value",M,"function decodeCborValue("],
]);
const camel=stem=>stem.split("-").map((p,i)=>i===0?p:p[0].toUpperCase()+p.slice(1)).join("");
const CANDIDATES=Object.freeze(RAW.map(([stem,source,symbol])=>Object.freeze({file:`${stem}-status.fungi`,flow:`${camel(stem)}StatusCore`,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt","evidenceBound","outcomeSealed","releaseChecked"]),expected:string(`${stem.replaceAll("-","_")}_built`)})));
function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}
describe("40-file source-bound Fungi decision-core overlay wave 40",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);const source=readFileSync(join(ROOT,"packages-ts",c.source),"utf8");assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.flow}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
