//! DSS.wasm Milestone 1 — the ~400-point V_DPM differential re-run through REAL wasmtime.
//!
//! The Node differential test (galerina-core-security/tests/dss-supervisor-wasm-differential.test.mjs)
//! proves the DSS supervisor's decision core, run under Node's `WebAssembly`, equals the Stage-A
//! interpreter over a 386-point V_DPM state x effect matrix. This harness closes the engine-transfer
//! gap (U10): it feeds the SAME module and the SAME matrix through Wasmtime — the production embedder —
//! and asserts every verdict still equals the interpreter's. A pass is a THREE-way agreement:
//!     interpreter  ===  Node-WebAssembly  ===  wasmtime
//!
//! Fixture (generated by tools/export-differential-fixture.mjs; gitignored):
//!   fixtures/supervisor.wasm        the admitted supervisor module
//!   fixtures/interned-strings.json  [{handle,value}] — seeds the host `__str_eq` faithfully
//!   fixtures/matrix.json            {points:[{flow,args,expected(u32)}]}
//!
//! The module needs three host imports (all (i32,i32)->i32): `host.audit.write` + `host.audit.log`
//! (no-ops — the pure decision flows never call them; they exist only so the import table links) and
//! `host.__str_eq`, the interned-string-handle comparator the string-ARG flows use. Fuel metering is
//! ON (Milestone 0 discipline) so every call runs under an explicit budget, never ambient.

use std::collections::HashMap;
use std::path::PathBuf;
use wasmtime::{Caller, Config, Engine, Linker, Module, Store};

struct HostState {
    strings: HashMap<i32, String>,
}

fn fixture(name: &str) -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "fixtures", name].iter().collect()
}

fn read_json(name: &str) -> anyhow::Result<serde_json::Value> {
    let bytes = std::fs::read(fixture(name))
        .map_err(|e| anyhow::anyhow!("missing fixture {name}: {e} — run: node tools/export-differential-fixture.mjs"))?;
    Ok(serde_json::from_slice(&bytes)?)
}

#[test]
fn vdpm_decision_core_equals_stage_a_through_wasmtime() -> anyhow::Result<()> {
    let wasm = std::fs::read(fixture("supervisor.wasm"))
        .map_err(|e| anyhow::anyhow!("missing supervisor.wasm: {e} — run: node tools/export-differential-fixture.mjs"))?;
    let interned = read_json("interned-strings.json")?;
    let matrix = read_json("matrix.json")?;

    // seed the interned-string handle -> value table (what host.__str_eq consults)
    let mut strings = HashMap::new();
    for e in interned.as_array().expect("interned-strings is an array") {
        strings.insert(
            e["handle"].as_i64().expect("handle is int") as i32,
            e["value"].as_str().expect("value is string").to_string(),
        );
    }

    // fuel ON (Milestone 0 discipline): no ambient execution
    let mut config = Config::new();
    config.consume_fuel(true);
    let engine = Engine::new(&config)?;
    let module = Module::new(&engine, &wasm)?;

    // host imports. audit.write/audit.log are no-ops (never invoked by the pure decision core).
    // __str_eq is faithful: identity short-circuit, else compare the seeded string VALUES; an
    // unseeded handle is deny-ish (not-equal) — fail-closed, though every matrix handle is seeded.
    let mut linker: Linker<HostState> = Linker::new(&engine);
    linker.func_wrap("host", "audit.write", |_c: Caller<'_, HostState>, _a: i32, _b: i32| -> i32 { 0 })?;
    linker.func_wrap("host", "audit.log", |_c: Caller<'_, HostState>, _a: i32, _b: i32| -> i32 { 0 })?;
    linker.func_wrap("host", "__str_eq", |c: Caller<'_, HostState>, a: i32, b: i32| -> i32 {
        if a == b {
            return 1;
        }
        let s = &c.data().strings;
        match (s.get(&a), s.get(&b)) {
            (Some(x), Some(y)) => (x == y) as i32,
            _ => 0,
        }
    })?;

    let mut store = Store::new(&engine, HostState { strings });
    store.set_fuel(1_000_000_000)?;
    let instance = linker.instantiate(&mut store, &module)?;

    let points = matrix["points"].as_array().expect("matrix.points is an array");
    let mut checked = 0usize;
    let mut mismatches: Vec<String> = Vec::new();

    for pt in points {
        let flow = pt["flow"].as_str().expect("flow name");
        let args = pt["args"].as_array().expect("args array");
        let expected = pt["expected"].as_u64().expect("expected u32");
        let a0 = args[0]["value"].as_i64().expect("arg0 int") as i32;

        store.set_fuel(100_000_000)?; // fresh explicit budget per call — never ambient
        let got: i32 = match args.len() {
            1 => {
                let f = instance.get_typed_func::<i32, i32>(&mut store, flow)?;
                f.call(&mut store, a0)?
            }
            2 => {
                let a1 = args[1]["value"].as_i64().expect("arg1 int") as i32;
                let f = instance.get_typed_func::<(i32, i32), i32>(&mut store, flow)?;
                f.call(&mut store, (a0, a1))?
            }
            n => anyhow::bail!("unexpected arg count {n} for {flow}"),
        };

        // compare as u32 — bit 31 (emergency_mode) makes i32 sign an encoding artifact
        let got_u32 = got as u32 as u64;
        if got_u32 != expected {
            let detail = args
                .iter()
                .map(|a| a["value"].to_string())
                .collect::<Vec<_>>()
                .join(",");
            mismatches.push(format!("{flow}({detail}): wasmtime={got_u32} != expected={expected}"));
        }
        checked += 1;
    }

    assert!(
        mismatches.is_empty(),
        "{} of {} points diverged through real wasmtime:\n{}",
        mismatches.len(),
        checked,
        mismatches.join("\n")
    );
    assert!(checked >= 380, "differential coverage too low: only {checked} points (fixture incomplete)");
    println!("wasmtime V_DPM differential: {checked} points — interpreter === Node-WASM === wasmtime OK");
    Ok(())
}
