// Plan contracts barrel (TODO pass, Grok 2026-10-05; zero-trust defaults, owner may revisit).
// Re-exports closed-shape ComputePlan / estimateTarget. No CLI wiring / report writer yet.

export {
  FUNGI_PLAN_001,
  FUNGI_PLAN_002,
  FUNGI_PLAN_003,
  FUNGI_PLAN_004,
  PLAN_RUNTIME_TARGETS,
  PLAN_GPU_SUITABILITIES,
  PLAN_OPTICAL_NEEDS,
  PLAN_OPTICAL_MODES,
  PLAN_OPTICAL_FALLBACK_TARGETS,
  PLAN_WASM_TARGETS,
  PLAN_GPU_SCHEMA,
  PLAN_OPTICAL_SCHEMA,
  PLAN_COMPAT_SCHEMA,
  COMPUTE_PLAN_FIELDS,
  PLAN_GPU_FIELDS,
  PLAN_OPTICAL_FIELDS,
  PLAN_COMPAT_FIELDS,
  PLAN_WORKSPACE_FIELDS,
  PLAN_OPTIONS_FIELDS,
  isPlanRuntimeTarget,
  isPlanGpuSuitability,
  isPlanOpticalNeed,
  isPlanOpticalMode,
  isPlanOpticalFallbackTarget,
  isPlanWasmTarget,
  estimateTarget,
  createComputePlan,
  readComputePlan,
} from "./plan/plan-contracts.js";

export type {
  PlanRuntimeTarget,
  PlanGpuSuitability,
  PlanOpticalNeed,
  PlanOpticalMode,
  PlanOpticalFallbackTarget,
  PlanWasmTarget,
  PlanDiagnosticField,
  PlanDiagnostic,
  PlanGpuPlan,
  PlanOpticalPlan,
  PlanCompatibility,
  PlanWorkspaceInput,
  PlanOptions,
  ComputePlan,
  ReadComputePlanResult,
} from "./plan/plan-contracts.js";
