// roadmap-generator.test.mjs — proves selected-root, preflighted
// roadmap/SVG generation and non-mutating whole-artifact drift refusal.
// Version: 1.0.0 · Task 7 generator governance.
// Related: scripts/gen-roadmap.mjs; scripts/component-health.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  linkSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { createHash } from "node:crypto";

const SCRIPT = resolve("scripts/gen-roadmap.mjs");
const PROVENANCE = resolve("scripts/lib/provenance.mjs");
const ROADMAP_EVIDENCE = resolve("scripts/lib/assurance-fabric/roadmap-evidence.mjs");
const GENERATED_EVIDENCE = resolve("scripts/lib/assurance-fabric/generated-evidence.mjs");
const EVIDENCE_DAG = resolve("scripts/lib/assurance-fabric/evidence-dag.mjs");
const STRICT_JSON = resolve("scripts/lib/assurance-fabric/strict-json.mjs");
const DEPENDENCIES = resolve("governance/assurance-evidence-dependencies.json");
const TOOLING_POLICY = resolve("governance/tooling-policy.json");
const BEGIN =
  "<!-- ROADMAP:BEGIN (generated by scripts/gen-roadmap.mjs — do not edit; run `node scripts/gen-roadmap.mjs --write`) -->";
const END = "<!-- ROADMAP:END -->";

/**
 * Write one fixture file, creating its parent directories.
 *
 * @param {string} root fixture root
 * @param {string} relativePath fixture-relative path
 * @param {string} content exact content
 */
function write(root, relativePath, content) {
  const path = join(root, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/**
 * Install hand-derived ledgers, component-health output, and the one
 * marker-owned canonical roadmap in one repository root.
 */
function installRepository(root) {
  const stageNames = [
    "lexer",
    "parser",
    "type-checker",
    "effect-checker",
    "gir-emitter",
    "governance-verifier",
    "runtime",
  ];
  write(
    root,
    "docs/security/rd0528-compiler-stage-hashes-baseline.json",
    JSON.stringify({
      stages: Object.fromEntries(stageNames.map((name) => [name, { sha256: name }])),
    }),
  );
  write(
    root,
    "docs/security/rd0528-compiler-authoritative-stages.json",
    JSON.stringify({ twins: [{ file: "lexer.fungi" }] }),
  );
  write(
    root,
    "docs/security/rd0361-authoritative-twins.json",
    JSON.stringify({ twins: [{ file: "memory.fungi" }] }),
  );
  write(
    root,
    "version.json",
    JSON.stringify({ version: "0.0.1", packageCount: 2, testCount: 3 }),
  );
  const percentAudit = {
    shipReadinessPct: 25,
    ztAvg: 50,
    buildAvg: 75,
    provenance: { branch: "fixture", sha: "fixture", dirty: true },
    sections: [
      {
        key: "zero-trust-thesis",
        rows: [{ label: "Boundary", pct: 50, evidence: { live: "fixture" } }],
      },
      {
        key: "build-progress",
        rows: [{ label: "Layer", pct: 75, evidence: { asserted: "fixture" } }],
      },
      {
        key: "tracking-registry",
        rows: [{ item: "Workstream", state: "building" }],
      },
    ],
  };
  write(
    root,
    "scripts/component-health.mjs",
    `console.log(${JSON.stringify(JSON.stringify({ percentAudit }))});\n`,
  );
  write(root, "README.md", "canonical roadmap: docs/ROADMAP.md\r\n");
  write(root, "docs/ROADMAP.md", `before\r\n${BEGIN}\r\nstale\r\n${END}\r\nafter\r\n`);
  write(root, "packages-ts/fixture/.graph/BOUNDARY.md", "generated boundary\n");
  write(root, "packages-ts/fixture/src/index.ts", "export const authority = 1;\n");
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function installEvidence(root, head) {
  const dependencies = JSON.parse(readFileSync(DEPENDENCIES, "utf8"));
  dependencies.root = {
    ...dependencies.root,
    id: "roadmap",
    evidencePath: "build/roadmap/roadmap.svg",
    toolPath: "scripts/gen-roadmap.mjs",
    expectedTool: "gen-roadmap",
  };
  write(root, "governance/assurance-evidence-dependencies.json", `${JSON.stringify(dependencies, undefined, 2)}\n`);
  write(root, "governance/tooling-policy.json", readFileSync(TOOLING_POLICY, "utf8"));
  write(root, "scripts/lib/assurance-fabric/roadmap-evidence.mjs", readFileSync(ROADMAP_EVIDENCE, "utf8"));
  write(root, "scripts/lib/assurance-fabric/generated-evidence.mjs", readFileSync(GENERATED_EVIDENCE, "utf8"));
  write(root, "scripts/lib/assurance-fabric/evidence-dag.mjs", readFileSync(EVIDENCE_DAG, "utf8"));
  write(root, "scripts/lib/assurance-fabric/strict-json.mjs", readFileSync(STRICT_JSON, "utf8"));
  for (const node of dependencies.nodes) {
    for (const artifactPath of node.artifactPaths) write(root, artifactPath, `${node.id}:${artifactPath}\n`);
    if (node.toolPath !== "scripts/component-health.mjs") {
      write(root, node.toolPath, `export const tool = ${JSON.stringify(node.expectedTool)};\n`);
    }
    const external = node.externalInputPolicy === "required"
      ? { externalInputDigest: sha256(`${node.id}:external`), externalDocumentCount: 1 }
      : {};
    write(root, node.provenancePath, `${JSON.stringify({
      tool: node.expectedTool,
      authority: "NONE",
      gitCommit: head,
      builtAt: "2026-08-10T00:00:00.000Z",
      node: process.version,
      ...external,
    }, undefined, 2)}\n`);
  }
  write(root, dependencies.root.toolPath, readFileSync(SCRIPT, "utf8"));
}

/**
 * Keep the copied generator harness distinct from the selected repository.
 */
function fixture() {
  const harness = mkdtempSync(join(tmpdir(), "roadmap-generator-"));
  const selected = join(harness, "selected");
  write(harness, "package.json", '{"type":"module"}\n');
  write(harness, "scripts/gen-roadmap.mjs", readFileSync(SCRIPT, "utf8"));
  write(harness, "scripts/lib/provenance.mjs", readFileSync(PROVENANCE, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/roadmap-evidence.mjs", readFileSync(ROADMAP_EVIDENCE, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/generated-evidence.mjs", readFileSync(GENERATED_EVIDENCE, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/evidence-dag.mjs", readFileSync(EVIDENCE_DAG, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/strict-json.mjs", readFileSync(STRICT_JSON, "utf8"));
  installRepository(harness);
  installRepository(selected);
  installEvidence(selected, "0".repeat(40));
  assert.equal(spawnSync("git", ["init"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["config", "user.email", "fixture@example.invalid"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["config", "user.name", "Fixture"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["add", "--", "."], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["commit", "-m", "fixture"], { cwd: selected }).status, 0);
  const head = spawnSync("git", ["rev-parse", "HEAD"], { cwd: selected, encoding: "utf8" }).stdout.trim();
  installEvidence(selected, head);
  return { harness, selected };
}

/**
 * Run the copied real generator against the selected fixture root.
 *
 * @param {string} harness harness root
 * @param {string} selected selected repository root
 * @param {readonly string[]} args generator mode arguments
 */
function run(harness, selected, args = []) {
  return spawnSync(
    process.execPath,
    [join(harness, "scripts", "gen-roadmap.mjs"), "--root", selected, ...args],
    {
      encoding: "utf8",
      env: { ...process.env, SOURCE_DATE_EPOCH: "1700000000" },
    },
  );
}

test("canonical roadmap preflights and checks every selected-root output without rewriting README", () => {
  const { harness, selected } = fixture();
  const svg = join(selected, "build/roadmap/roadmap.svg");
  const provenance = join(selected, "build/roadmap/provenance.json");
  const readme = join(selected, "README.md");
  const roadmap = join(selected, "docs/ROADMAP.md");
  try {
    const readmeOriginal = readFileSync(readme, "utf8");
    const missing = run(harness, selected, ["--check"]);
    assert.notEqual(missing.status, 0);
    assert.equal(existsSync(svg), false);

    const generated = run(harness, selected, ["--write"]);
    assert.equal(generated.status, 0, generated.stderr);
    assert.equal(existsSync(svg), true);
    assert.equal(existsSync(provenance), true);
    assert.equal(readFileSync(readme, "utf8"), readmeOriginal);
    assert.match(readFileSync(roadmap, "utf8"), /Tracking registry \(1\)/);
    assert.match(readFileSync(roadmap, "utf8"), /Assurance DAG: UNKNOWN/);
    assert.match(readFileSync(svg, "utf8"), /Workstream/);
    assert.match(readFileSync(svg, "utf8"), /Assurance DAG: UNKNOWN/);
    assert.equal(run(harness, selected, ["--check"]).status, 0);

    writeFileSync(svg, "tampered\n");
    const readmeBefore = readFileSync(readme, "utf8");
    const roadmapBefore = readFileSync(roadmap, "utf8");
    const drifted = run(harness, selected, ["--check"]);
    assert.notEqual(drifted.status, 0);
    assert.equal(readFileSync(svg, "utf8"), "tampered\n");
    assert.equal(readFileSync(readme, "utf8"), readmeBefore);
    assert.equal(readFileSync(roadmap, "utf8"), roadmapBefore);

    assert.equal(run(harness, selected, ["--write"]).status, 0);
    const svgBefore = readFileSync(svg, "utf8");
    writeFileSync(roadmap, "markerless\n");
    const unsafeWrite = run(harness, selected, ["--write"]);
    assert.notEqual(unsafeWrite.status, 0);
    assert.equal(readFileSync(svg, "utf8"), svgBefore);

    installRepository(selected);
    assert.equal(run(harness, selected, ["--write"]).status, 0);
    writeFileSync(provenance, "tampered\n");
    const provenanceDrift = run(harness, selected, ["--check"]);
    assert.notEqual(provenanceDrift.status, 0);
    assert.equal(readFileSync(provenance, "utf8"), "tampered\n");
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});

test("roadmap admits declared package graph output dirt but refuses source dirt", () => {
  const { harness, selected } = fixture();
  try {
    const initial = run(harness, selected, ["--write"]);
    assert.equal(initial.status, 0, `${initial.stdout}\n${initial.stderr}`);

    writeFileSync(
      join(selected, "packages-ts/fixture/.graph/BOUNDARY.md"),
      "refreshed generated boundary\n",
    );
    const generatedDirt = run(harness, selected, ["--write"]);
    assert.equal(generatedDirt.status, 0, `${generatedDirt.stdout}\n${generatedDirt.stderr}`);

    writeFileSync(
      join(selected, "packages-ts/fixture/src/index.ts"),
      "export const authority = 2;\n",
    );
    const sourceDirt = run(harness, selected, ["--write"]);
    assert.notEqual(sourceDirt.status, 0);
    assert.match(sourceDirt.stderr, /relevant provenance input is dirty/i);
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});

test("dirty roadmap preview is visibly non-authoritative and leaves canonical outputs untouched", () => {
  const { harness, selected } = fixture();
  const canonicalSvg = join(selected, "build/roadmap/roadmap.svg");
  const canonicalProvenance = join(selected, "build/roadmap/provenance.json");
  const canonicalDoc = join(selected, "docs/ROADMAP.md");
  const previewSvg = join(selected, "build/roadmap/roadmap-preview.svg");
  try {
    const initial = run(harness, selected, ["--write"]);
    assert.equal(initial.status, 0, `${initial.stdout}\n${initial.stderr}`);
    const before = [canonicalSvg, canonicalProvenance, canonicalDoc]
      .map((path) => readFileSync(path, "utf8"));
    const head = spawnSync("git", ["rev-parse", "HEAD"], {
      cwd: selected,
      encoding: "utf8",
    }).stdout.trim();
    write(selected, "packages-ts/fixture/src/index.ts", "export const authority = 2;\n");

    const preview = run(harness, selected, ["--preview"]);
    assert.equal(preview.status, 0, `${preview.stdout}\n${preview.stderr}`);
    const image = readFileSync(previewSvg, "utf8");
    assert.match(image, /PREVIEW ONLY.*NON-AUTHORITATIVE/u);
    assert.match(image, new RegExp(head, "u"));
    assert.match(image, /1 relevant dirty input/u);
    assert.deepEqual(
      [canonicalSvg, canonicalProvenance, canonicalDoc].map((path) => readFileSync(path, "utf8")),
      before,
    );
    const canonicalCheck = run(harness, selected, ["--check"]);
    assert.notEqual(canonicalCheck.status, 0);
    assert.match(canonicalCheck.stderr, /relevant provenance input is dirty/u);
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});

test("preview publication cannot overwrite a hard-linked canonical document", () => {
  const { harness, selected } = fixture();
  const canonicalDoc = join(selected, "docs/ROADMAP.md");
  const previewSvg = join(selected, "build/roadmap/roadmap-preview.svg");
  try {
    const before = readFileSync(canonicalDoc, "utf8");
    mkdirSync(dirname(previewSvg), { recursive: true });
    linkSync(canonicalDoc, previewSvg);
    const result = run(harness, selected, ["--preview"]);
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    assert.equal(readFileSync(canonicalDoc, "utf8"), before);
    assert.match(readFileSync(previewSvg, "utf8"), /PREVIEW ONLY.*NON-AUTHORITATIVE/u);
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});

test("roadmap renders stale predecessors as unknown and refuses deny evidence", () => {
  const { harness, selected } = fixture();
  const svg = join(selected, "build/roadmap/roadmap.svg");
  try {
    assert.equal(run(harness, selected, ["--write"]).status, 0);
    const graphProvenance = join(selected, "build/graph/provenance.json");
    const stale = JSON.parse(readFileSync(graphProvenance, "utf8"));
    stale.gitCommit = "b".repeat(40);
    writeFileSync(graphProvenance, `${JSON.stringify(stale, undefined, 2)}\n`);
    const unknown = run(harness, selected, ["--write"]);
    assert.equal(unknown.status, 0, unknown.stderr);
    assert.match(readFileSync(svg, "utf8"), /Assurance DAG: UNKNOWN/);

    writeFileSync(join(selected, "build/kb-graph/provenance.json"), "{\"tool\":\"kb-graph-generator\"}\n");
    const before = readFileSync(svg, "utf8");
    const denied = run(harness, selected, ["--write"]);
    assert.notEqual(denied.status, 0);
    assert.equal(readFileSync(svg, "utf8"), before);

    installEvidence(selected, spawnSync("git", ["rev-parse", "HEAD"], {
      cwd: selected,
      encoding: "utf8",
    }).stdout.trim());
    assert.equal(run(harness, selected, ["--write"]).status, 0);
    const semanticBefore = readFileSync(svg, "utf8");
    writeFileSync(join(selected, "build/assurance-semantic-graph/provenance.json"), "{\n");
    const semanticDenied = run(harness, selected, ["--write"]);
    assert.notEqual(semanticDenied.status, 0);
    assert.equal(readFileSync(svg, "utf8"), semanticBefore);
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});

test("roadmap provenance is exact and stable across its own output-only commits", () => {
  const { harness, selected } = fixture();
  const provenancePath = join(selected, "build/roadmap/provenance.json");
  const svgPath = join(selected, "build/roadmap/roadmap.svg");
  try {
    const sourceCommit = spawnSync("git", ["rev-parse", "HEAD"], {
      cwd: selected,
      encoding: "utf8",
    }).stdout.trim();
    const generated = run(harness, selected, ["--write"]);
    assert.equal(generated.status, 0, `${generated.stdout}\n${generated.stderr}`);
    const published = JSON.parse(readFileSync(provenancePath, "utf8"));
    assert.equal(published.schemaVersion, 1);
    assert.equal(published.authority, "NONE");
    assert.equal(published.gitCommit, sourceCommit);
    assert.match(published.authoritativeInputsDigest, /^[0-9a-f]{64}$/u);
    assert.match(readFileSync(svgPath, "utf8"), /Assurance DAG: UNKNOWN/);

    assert.equal(spawnSync("git", ["add", "--",
      "docs/ROADMAP.md",
      "build/roadmap/roadmap.svg",
      "build/roadmap/provenance.json",
    ], { cwd: selected }).status, 0);
    assert.equal(spawnSync("git", ["commit", "-m", "roadmap generated outputs"], {
      cwd: selected,
    }).status, 0);
    const afterOutputCommit = run(harness, selected, ["--check"]);
    assert.equal(
      afterOutputCommit.status,
      0,
      `${afterOutputCommit.stdout}\n${afterOutputCommit.stderr}`,
    );
    assert.deepEqual(JSON.parse(readFileSync(provenancePath, "utf8")), published);
    assert.match(readFileSync(svgPath, "utf8"), /Assurance DAG: UNKNOWN/);

    const ledgerPath = join(selected, "docs/security/rd0361-authoritative-twins.json");
    writeFileSync(ledgerPath, JSON.stringify({ twins: [{ file: "changed-memory.fungi" }] }));
    assert.equal(spawnSync("git", ["add", "--", "docs/security/rd0361-authoritative-twins.json"], {
      cwd: selected,
    }).status, 0);
    assert.equal(spawnSync("git", ["commit", "-m", "change roadmap authority input"], {
      cwd: selected,
    }).status, 0);
    const inputCommit = spawnSync("git", ["rev-parse", "HEAD"], {
      cwd: selected,
      encoding: "utf8",
    }).stdout.trim();
    const refreshed = run(harness, selected, ["--write"]);
    assert.equal(refreshed.status, 0, `${refreshed.stdout}\n${refreshed.stderr}`);
    const advanced = JSON.parse(readFileSync(provenancePath, "utf8"));
    assert.equal(advanced.gitCommit, inputCommit);
    assert.notEqual(advanced.authoritativeInputsDigest, published.authoritativeInputsDigest);

    const substituted = {
      ...advanced,
      gitCommit: advanced.gitCommit === "a".repeat(40) ? "c".repeat(40) : "a".repeat(40),
    };
    writeFileSync(provenancePath, `${JSON.stringify(substituted, undefined, 2)}\n`);
    const tampered = run(harness, selected, ["--check"]);
    assert.notEqual(tampered.status, 0);
    assert.deepEqual(JSON.parse(readFileSync(provenancePath, "utf8")), substituted);
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});
