#!/usr/bin/env node
// gen-roadmap.mjs — the canonical living ROADMAP generated from live ledgers.
//
// Why this exists: the README's "Where the project is" table was HAND-TYPED and had gone stale (it still
// described the RD-0528 authority cutover as entirely un-flipped after five stages had flipped). A status
// number that a human types is a claim; a status number a tool derives from the artifact that decides it is
// evidence. This tool derives EVERY position and EVERY station state from a live source, and — like
// gen-status-blocks.mjs — owns a marker-delimited region plus a `--check` drift gate so it cannot go stale
// again silently.
//
// It also makes the project's own honesty problem VISIBLE rather than buried in JSON: percent-audit rows
// carry an evidence class (live / ladder = measured, asserted = hand-typed debt). Measured stations are
// solid; asserted stations are hollow with a dashed ring. A map that is mostly hollow is telling the truth
// about itself.
//
//   node scripts/gen-roadmap.mjs               # print the markdown block to stdout
//   node scripts/gen-roadmap.mjs --write       # write the canonical document region + artifacts
//   node scripts/gen-roadmap.mjs --check       # exit 1 if any owned output is stale (the gate)
//   node scripts/gen-roadmap.mjs --preview     # write a visibly non-authoritative local SVG, even when dirty
//   node scripts/gen-roadmap.mjs --self-test   # DRIVE the generator with synthetic bad inputs
import { createHash, randomUUID } from "node:crypto";
import {
  closeSync,
  readFileSync,
  writeFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  openSync,
  realpathSync,
  renameSync,
  unlinkSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { join, dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { deriveRoadmapEvidence } from "./lib/assurance-fabric/roadmap-evidence.mjs";
import { exitOnHelp } from "./lib/cli-help.mjs";

exitOnHelp(import.meta.url, "usage: node scripts/gen-roadmap.mjs [--root <dir>] [--write|--check|--preview|--self-test]\n  --help, -h  print this usage and exit 0 without reading or writing");

/**
 * Parse one repository root and one output mode.
 */
function parseArgs(argv) {
  let root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  let rootSeen = false;
  let mode = "print";
  let modeSeen = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--root") {
      if (rootSeen || i + 1 >= argv.length || argv[i + 1].startsWith("--")) {
        throw new Error("roadmap: --root requires exactly one path");
      }
      root = resolve(argv[++i]);
      rootSeen = true;
      continue;
    }
    if (arg === "--write" || arg === "--check" || arg === "--preview" || arg === "--self-test") {
      if (modeSeen) throw new Error("roadmap: select exactly one mode");
      mode = arg.slice(2);
      modeSeen = true;
      continue;
    }
    throw new Error(`roadmap: unknown argument ${arg}`);
  }
  return { root, mode };
}

const OPTIONS = parseArgs(process.argv.slice(2));
const ROOT = OPTIONS.root;
const BEGIN = "<!-- ROADMAP:BEGIN (generated by scripts/gen-roadmap.mjs — do not edit; run `node scripts/gen-roadmap.mjs --write`) -->";
const END = "<!-- ROADMAP:END -->";
// One canonical living document carries the generated roadmap region.
const TARGETS = ["docs/ROADMAP.md"];
const SVG_OUT = join(ROOT, "build", "roadmap", "roadmap.svg");
const PREVIEW_OUT = join(ROOT, "build", "roadmap", "roadmap-preview.svg");
const PROVENANCE_OUT = join(ROOT, "build", "roadmap", "provenance.json");
const TOOL = "gen-roadmap";
const DESCRIPTOR_PATH = "governance/assurance-evidence-dependencies.json";
const TOOLING_POLICY_PATH = "governance/tooling-policy.json";
const GRAPH_GENERATOR_KEYS = Object.freeze([
  "scripts/package-graph-generator.mjs",
  "scripts/project-graph-generator.mjs",
  "scripts/kb-graph-generator.mjs",
  "scripts/dev-tool-index.mjs",
  "scripts/gen-assurance-semantic-graph.mjs",
]);
const GIT_IDENTITY = /^(?:[0-9a-f]{40}|[0-9a-f]{64})$/u;
const MAX_GIT_BYTES = 64 * 1024 * 1024;
const MAX_GIT_COMMITS = 100_000;
const MAX_INPUT_BYTES = 64 * 1024 * 1024;
const MAX_TOTAL_INPUT_BYTES = 512 * 1024 * 1024;
const AUTHORITATIVE_INPUT_DOMAIN = Buffer.from(
  "galerina.roadmap.authoritative-inputs.v2\0",
  "utf8",
);
const RELEVANT_ROOT_FILES = new Set([
  "AGENTS.md",
  "README.md",
  "galerina.mjs",
  "galerina.workspace.json",
  "version.json",
]);
const RELEVANT_PREFIXES = Object.freeze([
  "docs/",
  "examples/",
  "governance/",
  "packages-ts/",
  "proofs/",
  "scripts/",
  "tests/",
  "tools/",
]);
const ROADMAP_SUPPORT_PATHS = Object.freeze([
  "scripts/lib/assurance-fabric/roadmap-evidence.mjs",
  "scripts/lib/assurance-fabric/generated-evidence.mjs",
  "scripts/lib/assurance-fabric/evidence-dag.mjs",
  "scripts/lib/assurance-fabric/strict-json.mjs",
]);

// --- sources -------------------------------------------------------------------------------------------
// Each source is a FILE THAT DECIDES SOMETHING, not a doc that describes it. A missing/malformed source is
// fatal, never a silent zero: deny-by-default, because "0 authoritative stages" and "I could not read the
// ledger" must not render identically.
const SOURCES = Object.freeze({
  stageHashes: "docs/security/rd0528-compiler-stage-hashes-baseline.json", // enumerates the 7 compiler stages
  stageLedger: "docs/security/rd0528-compiler-authoritative-stages.json",  // which stages are AUTHORITATIVE
  kernelLedger: "docs/security/rd0361-authoritative-twins.json",           // kernel sentinel authority flips
  version: "version.json",                                                  // package + test counts
});

function loadJSON(rel) {
  const abs = join(ROOT, rel);
  if (!existsSync(abs)) throw new Error(`source missing: ${rel} (fail-closed — a roadmap with an unreadable ledger is not a roadmap)`);
  return JSON.parse(readFileSync(abs, "utf8"));
}

// component-health --json is the single source for the percentage sections (same source gen-status-blocks uses).
function percentAudit() {
  const r = spawnSync(process.execPath, [join(ROOT, "scripts", "component-health.mjs"), "--json"],
    { cwd: ROOT, encoding: "utf8", windowsHide: true, maxBuffer: 32 * 1024 * 1024 });
  if (r.status !== 0) throw new Error(`component-health --json failed (exit ${r.status})`);
  return JSON.parse(r.stdout).percentAudit;
}

function git(args, encoding = "utf8") {
  const result = spawnSync("git", args, {
    cwd: ROOT,
    encoding,
    windowsHide: true,
    maxBuffer: MAX_GIT_BYTES,
  });
  if (result.error || result.signal || result.status !== 0) {
    const reason = result.error?.message
      ?? (result.signal ? `signal ${result.signal}` : `exit ${String(result.status)}`);
    throw new Error(`roadmap provenance Git command failed (${args[0]}): ${reason}`);
  }
  return result.stdout;
}

function nulPaths(bytes, label, unique = true) {
  if (!Buffer.isBuffer(bytes)) throw new Error(`${label} did not return exact bytes`);
  let text;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch (error) {
    throw new Error(`${label} returned non-UTF-8 paths: ${error.message}`);
  }
  const paths = text.split("\0");
  if (paths.at(-1) !== "") throw new Error(`${label} omitted its final NUL delimiter`);
  paths.pop();
  if (unique && new Set(paths).size !== paths.length) throw new Error(`${label} returned duplicate paths`);
  return paths;
}

function canonicalRepositoryPath(path) {
  return typeof path === "string"
    && path.length > 0
    && path.length <= 1024
    && !path.includes("\\")
    && !path.startsWith("/")
    && !/^[A-Za-z]:/u.test(path)
    && path.split("/").every((segment) => (
      segment.length > 0 && segment !== "." && segment !== ".."
    ));
}

let graphOutputs;
function declaredGraphOutputs() {
  if (graphOutputs !== undefined) return graphOutputs;
  let policy;
  try {
    policy = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(
      boundedInput(TOOLING_POLICY_PATH),
    ));
  } catch (error) {
    throw new Error(`roadmap tooling policy refused: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (
    policy === null
    || typeof policy !== "object"
    || Array.isArray(policy)
    || policy.generators === null
    || typeof policy.generators !== "object"
    || Array.isArray(policy.generators)
  ) {
    throw new Error("roadmap tooling policy has no ordinary generator registry");
  }
  const outputs = new Set();
  for (const key of GRAPH_GENERATOR_KEYS) {
    const descriptor = Object.getOwnPropertyDescriptor(policy.generators, key);
    const value = descriptor?.value;
    if (
      descriptor === undefined
      || descriptor.get !== undefined
      || descriptor.set !== undefined
      || value === null
      || typeof value !== "object"
      || Array.isArray(value)
      || !Array.isArray(value.outputs)
      || value.outputs.length === 0
      || value.outputs.length > 1024
    ) {
      throw new Error(`roadmap tooling policy has no closed output set for ${key}`);
    }
    for (const path of value.outputs) {
      if (!canonicalRepositoryPath(path) || outputs.has(path)) {
        throw new Error(`roadmap tooling policy has a malformed or duplicate graph output for ${key}`);
      }
      outputs.add(path);
    }
  }
  graphOutputs = Object.freeze(outputs);
  return graphOutputs;
}

function declaredGeneratedGraphPath(path) {
  return declaredGraphOutputs().has(path)
    || /^packages-ts\/[^/]+\/\.graph\/(?:BOUNDARY\.md|package-graph\.json)$/u.test(path);
}

function relevantOrdinaryPath(path) {
  if (TARGETS.includes(path)) return false;
  if (declaredGeneratedGraphPath(path)) return false;
  return RELEVANT_ROOT_FILES.has(path)
    || RELEVANT_PREFIXES.some((prefix) => path.startsWith(prefix));
}

function gitFile(commit, path) {
  const listing = git(["ls-tree", "-z", "--full-tree", commit, "--", path], null);
  if (listing.length === 0) return undefined;
  const records = listing.toString("utf8").split("\0");
  if (records.at(-1) !== "") throw new Error("Git tree listing omitted its final NUL delimiter");
  records.pop();
  if (records.length !== 1) throw new Error(`Git tree listing did not identify exactly one ${path}`);
  const match = /^(100644|100755) blob ([0-9a-f]{40}|[0-9a-f]{64})\t(.+)$/u.exec(records[0]);
  if (!match || match[3] !== path) {
    throw new Error(`Git tree listing contains a non-regular or mismatched roadmap target ${path}`);
  }
  return git(["show", `${commit}:${path}`], null);
}

// The compiler pipeline ORDER is an authored fact (the stages run in this sequence); MEMBERSHIP is derived.
// The assertion below is what keeps the authored half honest: add or remove a stage in the ledger and this
// throws rather than quietly dropping a station off the map.
const PIPELINE_ORDER = Object.freeze([
  "lexer", "parser", "type-checker", "effect-checker", "gir-emitter", "governance-verifier", "runtime",
]);

export function stageLine(hashBaseline, ledger) {
  const known = Object.keys(hashBaseline?.stages ?? {});
  if (known.length === 0) throw new Error("stage-hash baseline lists no stages — fail-closed");
  const missing = known.filter((s) => !PIPELINE_ORDER.includes(s));
  const extra = PIPELINE_ORDER.filter((s) => !known.includes(s));
  if (missing.length || extra.length) {
    throw new Error(`PIPELINE_ORDER is out of sync with the stage ledger (unplaced: ${missing.join(",") || "none"} · phantom: ${extra.join(",") || "none"}) — fix the order list, do not render a partial map`);
  }
  // A stage is AUTHORITATIVE iff it has a ledger entry; the ledger names files, so strip the extension.
  const flipped = new Set((ledger?.twins ?? []).map((t) => String(t.file ?? "").replace(/\.fungi$/, "")));
  return PIPELINE_ORDER.map((name) => ({
    name,
    authoritative: flipped.has(name),
    // Every stage in the baseline is byte-pinned; that is the R3 evidence the flip ladder stands on.
    pinned: Boolean(hashBaseline.stages[name]?.sha256),
  }));
}

// Evidence class of a percent-audit row: measured (a live reading or a countable ladder) vs asserted (typed).
export function evidenceClass(row) {
  const e = row?.evidence;
  if (!e) return "none";                                     // a WORD row carries no number to evidence
  if (e.live) return "live";                                 // read from a live artifact every run
  if (Array.isArray(e.ladder) && e.ladder.length) return "ladder"; // derived from a countable set
  return "asserted";                                         // hand-typed debt — the class we are burning down
}

// --- the map -------------------------------------------------------------------------------------------
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// Palette: one hue per line, plus a neutral for the un-measured. Deliberately NOT the accent-on-dark cliche;
// these are transit-map inks on paper, which is the idiom the owner asked for.
const LINES = Object.freeze({
  selfhost: "#c8102e", // red line — compiler self-hosting (RD-0528)
  thesis: "#0f7b6c",   // green line — Zero-Trust thesis boundaries
  build: "#1c5ea8",    // blue line — build progress
  kernel: "#b8860b",   // amber line — kernel execution cutover (RD-0361)
});

function station(x, y, colour, filled, measured) {
  // Filled = reached/authoritative. Dashed ring = the number is ASSERTED, not measured — the map refuses to
  // let a hand-typed percentage look identical to a derived one.
  const dash = measured ? "" : ` stroke-dasharray="3 2.5"`;
  return `<circle cx="${x}" cy="${y}" r="6.5" fill="${filled ? colour : "var(--paper)"}" stroke="${colour}" stroke-width="2.75"${dash}/>`;
}

export function renderSVG({ stages, thesis, build, kernel, meta, assurance }, preview = undefined) {
  // The current labels are materially longer than the original July map.
  // Keep a real label gutter and a right evidence gutter so neither the
  // longest layer name nor the asserted marker is clipped in the SVG itself.
  const W = 1600, PAD_L = 360, PAD_R = 130, TRACK = W - PAD_L - PAD_R;
  const x = (pct) => PAD_L + (TRACK * pct) / 100;
  const out = [];
  let y = 96;

  const rowLabel = (text, sub) =>
    `<text x="${PAD_L - 18}" y="${y + 4}" text-anchor="end" class="stn">${esc(text)}</text>` +
    (sub ? `<text x="${PAD_L - 18}" y="${y + 18}" text-anchor="end" class="sub">${esc(sub)}</text>` : "");

  // --- Line 1: compiler self-hosting. An ORDINAL line — stations are stages in pipeline order, evenly
  // spaced, because "how far along the pipeline" is a sequence, not a percentage. Fill = authority flipped.
  out.push(`<text x="${PAD_L - 18}" y="${y - 34}" text-anchor="end" class="line-name" fill="${LINES.selfhost}">Self-hosting</text>`);
  out.push(`<text x="${PAD_L - 18}" y="${y - 20}" text-anchor="end" class="sub">RD-0528 · authority ladder</text>`);
  const sx = (i) => PAD_L + (TRACK * i) / (stages.length - 1);
  out.push(`<line x1="${sx(0)}" y1="${y}" x2="${sx(stages.length - 1)}" y2="${y}" stroke="${LINES.selfhost}" stroke-width="7" stroke-linecap="round" opacity="0.9"/>`);
  stages.forEach((s, i) => {
    out.push(station(sx(i), y, LINES.selfhost, s.authoritative, true)); // every stage is byte-pinned: measured
    out.push(`<text x="${sx(i)}" y="${y - 16}" text-anchor="middle" class="stn">${esc(s.name)}</text>`);
    out.push(`<text x="${sx(i)}" y="${y + 24}" text-anchor="middle" class="sub">${s.authoritative ? "authoritative" : "differential"}</text>`);
  });
  y += 74;

  // --- Line 4 rides here too: the kernel cutover is also ordinal (a count of flipped sentinels), so it gets
  // a short interchange stub rather than a full percentage track — it has no denominator in any ledger.
  out.push(`<text x="${PAD_L - 18}" y="${y + 4}" text-anchor="end" class="line-name" fill="${LINES.kernel}">Kernel cutover</text>`);
  out.push(`<text x="${PAD_L - 18}" y="${y + 18}" text-anchor="end" class="sub">RD-0361 · sentinel twins</text>`);
  const kx = (i) => PAD_L + 26 * i;
  out.push(`<line x1="${kx(0)}" y1="${y}" x2="${kx(Math.max(kernel.length - 1, 0))}" y2="${y}" stroke="${LINES.kernel}" stroke-width="7" stroke-linecap="round" opacity="0.9"/>`);
  kernel.forEach((_, i) => out.push(station(kx(i), y, LINES.kernel, true, true)));
  out.push(`<text x="${kx(Math.max(kernel.length - 1, 0)) + 22}" y="${y + 4}" class="sub">${kernel.length} authoritative in the ledger · the differential remainder has no ledger denominator (not counted here)</text>`);
  y += 76;

  // --- Percentage lines: x-position IS the number. A station's horizontal place cannot be prettified.
  const scaleY = y;
  out.push(`<line x1="${x(0)}" y1="${scaleY}" x2="${x(100)}" y2="${scaleY}" stroke="var(--rule)" stroke-width="1"/>`);
  for (let p = 0; p <= 100; p += 25) {
    out.push(`<line x1="${x(p)}" y1="${scaleY - 4}" x2="${x(p)}" y2="${scaleY + 4}" stroke="var(--rule)" stroke-width="1"/>`);
    out.push(`<text x="${x(p)}" y="${scaleY - 10}" text-anchor="middle" class="sub">${p}%</text>`);
  }
  y += 34;

  const pctLine = (title, sub, colour, rows) => {
    out.push(`<text x="${PAD_L - 18}" y="${y - 12}" text-anchor="end" class="line-name" fill="${colour}">${esc(title)}</text>`);
    out.push(`<text x="${PAD_L - 18}" y="${y + 2}" text-anchor="end" class="sub">${esc(sub)}</text>`);
    for (const r of rows) {
      y += 26;
      out.push(rowLabel(r.label));
      // The track runs 0 → the row's actual percentage. The gap to 100% is the work left, drawn to scale.
      out.push(`<line x1="${x(0)}" y1="${y}" x2="${x(100)}" y2="${y}" stroke="var(--rule)" stroke-width="1.5" stroke-dasharray="2 4"/>`);
      out.push(`<line x1="${x(0)}" y1="${y}" x2="${x(r.pct)}" y2="${y}" stroke="${colour}" stroke-width="6" stroke-linecap="round" opacity="0.9"/>`);
      out.push(station(x(r.pct), y, colour, r.measured, r.measured));
      out.push(`<text x="${x(r.pct) + 13}" y="${y + 4}" class="pct">${r.pct}%</text>`);
      if (!r.measured) out.push(`<text x="${x(r.pct) + 46}" y="${y + 4}" class="sub">asserted</text>`);
    }
    y += 40;
  };

  pctLine("Zero-Trust thesis", "the five trust boundaries", LINES.thesis, thesis);
  pctLine("Build progress", "layers with a number", LINES.build, build);

  // --- Tracking registry: every named workstream (owner catch 2026-07-25 — the first cut dropped this
  // section entirely, so DSS.wasm / .spore / TritMesh simply vanished from the map). Grouped by every
  // admitted registry state: shipped = solid; building = hollow; design/build-pending and post-v1 =
  // hollow + dashed. An unknown state refuses instead of silently dropping a workstream.
  if (meta.registry.length) {
    const groups = [
      ["shipped", true, ""],
      ["building", false, ""],
      ["design-done", false, ` stroke-dasharray="3 2.5"`],
      ["build-pending", false, ` stroke-dasharray="3 2.5"`],
      ["post-v1", false, ` stroke-dasharray="3 2.5"`],
    ];
    const admittedStates = new Set(groups.map(([state]) => state));
    const unknownStates = [...new Set(meta.registry.map((row) => row.state).filter((state) => !admittedStates.has(state)))];
    if (unknownStates.length > 0) {
      throw new Error(`roadmap: unrendered tracking-registry state(s): ${unknownStates.join(", ")}`);
    }
    out.push(`<text x="${PAD_L - 18}" y="${y}" text-anchor="end" class="line-name" fill="${LINES.build}">Tracking registry</text>`);
    out.push(`<text x="${PAD_L - 18}" y="${y + 14}" text-anchor="end" class="sub">${meta.registry.length} named workstreams</text>`);
    for (const [state, filled, dash] of groups) {
      const items = meta.registry.filter((r) => r.state === state);
      if (!items.length) continue;
      out.push(`<text x="${x(0)}" y="${y}" class="stn">${esc(state)} (${items.length})</text>`);
      y += 20;
      // Two columns so the registry does not double the map's height.
      items.forEach((r, i) => {
        const cx = x(0) + (i % 2) * ((TRACK / 2) | 0), cy = y + Math.floor(i / 2) * 20;
        out.push(`<circle cx="${cx}" cy="${cy}" r="5" fill="${filled ? LINES.build : "var(--paper)"}" stroke="${LINES.build}" stroke-width="2"${dash}/>`);
        out.push(`<text x="${cx + 12}" y="${cy + 4}" class="sub">${esc(r.item)}</text>`);
      });
      y += Math.ceil(items.length / 2) * 20 + 14;
    }
    y += 12;
  }

  // --- WORD rows: layers with no percentage at all. They belong on the map as terminus markers, because
  // omitting them would make the map look more complete than the project is.
  if (meta.wordRows.length) {
    out.push(`<text x="${PAD_L - 18}" y="${y}" text-anchor="end" class="line-name" fill="var(--ink)">Not a number</text>`);
    out.push(`<text x="${PAD_L - 18}" y="${y + 14}" text-anchor="end" class="sub">no percentage claimed</text>`);
    meta.wordRows.forEach((label, i) => {
      const ly = y + i * 22;
      out.push(`<circle cx="${x(0)}" cy="${ly}" r="5" fill="none" stroke="var(--ink)" stroke-width="2" stroke-dasharray="3 2.5"/>`);
      out.push(`<text x="${x(0) + 14}" y="${ly + 4}" class="stn">${esc(label)}</text>`);
    });
    y += meta.wordRows.length * 22 + 24;
  }

  const H = y + 76;
  const legend = [
    ["solid station", "reached / authority flipped"],
    ["hollow station", "not yet reached"],
    ["dashed ring", "the number is ASSERTED (hand-typed), not measured"],
  ].map(([k, v], i) => `<text x="${PAD_L}" y="${H - 54 + i * 15}" class="sub"><tspan class="stn">${esc(k)}</tspan> — ${esc(v)}</text>`).join("");

  const previewHeight = preview === undefined ? 0 : 46;
  const previewBanner = preview === undefined ? "" : `<rect x="0" y="0" width="${W}" height="${previewHeight}" fill="#904800"/>
<text x="20" y="29" style="fill:#fff;font-size:18px;font-weight:700">PREVIEW ONLY · NON-AUTHORITATIVE · HEAD ${esc(preview.head)} · ${preview.dirtyCount} relevant dirty input${preview.dirtyCount === 1 ? "" : "s"}</text>
<g transform="translate(0 ${previewHeight})">`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H + previewHeight}" width="${W}" height="${H + previewHeight}" role="img" aria-label="Galerina graph-owned roadmap${preview === undefined ? "" : " non-authoritative preview"}">
<style>
  :root { --paper:#fbfaf7; --ink:#1b1a17; --rule:#c9c4ba; }
  @media (prefers-color-scheme: dark) { :root { --paper:#16181c; --ink:#e8e6e1; --rule:#3a3f47; } }
  svg { background: var(--paper); }
  text { font-family: ui-sans-serif, "Segoe UI", system-ui, sans-serif; fill: var(--ink); }
  .stn { font-size: 12.5px; font-weight: 600; }
  .sub { font-size: 10.5px; fill: var(--ink); opacity: .62; }
  .pct { font-size: 12px; font-weight: 700; font-variant-numeric: tabular-nums; }
  .line-name { font-size: 13.5px; font-weight: 700; letter-spacing: .02em; }
  .title { font-size: 19px; font-weight: 700; }
</style>
<rect width="100%" height="100%" fill="var(--paper)"/>
${previewBanner}
<text x="${PAD_L - 18}" y="34" text-anchor="end" class="title">Where the project is</text>
<text x="${PAD_L}" y="34" class="sub">${esc(meta.caption)}</text>
<text x="${PAD_L}" y="50" class="sub">${esc(meta.provenance)}</text>
<text x="${PAD_L}" y="66" class="stn">Assurance DAG: ${esc(assurance.state)} · root ${esc(assurance.rootDigest)} · non-authorizing</text>
${out.join("\n")}
${legend}
${preview === undefined ? "" : "</g>"}
</svg>
`;
}

// --- the markdown block --------------------------------------------------------------------------------
// Deterministic: no clock. A timestamp would make every run drift and defeat the --check gate.
export function renderBlock(model) {
  const { stages, thesis, build, kernel, meta, assurance } = model;
  const flipped = stages.filter((s) => s.authoritative);
  const measured = [...thesis, ...build].filter((r) => r.measured).length;
  const total = thesis.length + build.length;
  const stageCell = (s) => `${s.authoritative ? "●" : "○"} ${s.name}`;
  return [
    BEGIN,
    `**${meta.caption}**`,
    ``,
    `**Assurance DAG: ${assurance.state}** · root \`${assurance.rootDigest}\` · non-authorizing.`,
    ``,
    `![Galerina graph-owned roadmap](../build/roadmap/roadmap.svg)`,
    ``,
    `**Self-hosting line (RD-0528).** ${flipped.length} of ${stages.length} compiler stages are AUTHORITATIVE — the \`.fungi\` stage is the decider of record and the co-located \`.ts\` is retained as a running differential shadow. All ${stages.length} are byte-pinned in the stage-hash baseline.`,
    ``,
    `| stage | ${stages.map((s) => s.name).join(" | ")} |`,
    `|---|${stages.map(() => "---").join("|")}|`,
    `| authority | ${stages.map(stageCell).map((c) => c.split(" ")[0]).join(" | ")} |`,
    ``,
    `**Kernel cutover line (RD-0361).** ${kernel.length} sentinel twins are authoritative in the ledger. The differential remainder is not counted here — no ledger records a denominator, and inventing one would be a hand-typed number.`,
    ``,
    `| Zero-Trust boundary | % | evidence |`,
    `|---|--:|---|`,
    ...thesis.map((r) => `| ${r.label} | ${r.pct}% | ${r.measured ? "measured" : "**asserted**"} |`),
    ``,
    `| Build-progress layer | % | evidence |`,
    `|---|--:|---|`,
    ...build.map((r) => `| ${r.label} | ${r.pct}% | ${r.measured ? "measured" : "**asserted**"} |`),
    ...(meta.wordRows.length ? [``, `**No percentage claimed:** ${meta.wordRows.join(" · ")}.`] : []),
    ``,
    `**Tracking registry (${meta.registry.length}):** ` + ["shipped", "building", "post-v1"]
      .map((s) => `${s} ${meta.registry.filter((r) => r.state === s).length}`).join(" · ")
      + ` — every named workstream, from the same percent-audit source; the map's registry section lists each one.`,
    ``,
    `> **Read the map honestly: ${measured} of ${total} percentages are measured** (a live reading or a countable ladder); the remaining ${total - measured} are asserted — a considered judgement, but hand-typed. Burning that ratio down is itself tracked work, which is why the map draws the difference instead of hiding it.`,
    ``,
    `<sub>${meta.provenance} · regenerate: \`node scripts/gen-roadmap.mjs --write\`</sub>`,
    END,
  ].join("\n");
}

// --- model assembly ------------------------------------------------------------------------------------
export function buildModel({ pa, hashBaseline, ledger, kernelLedger, version, assurance }) {
  const stages = stageLine(hashBaseline, ledger);
  const sect = (k) => pa.sections.find((s) => s.key === k) ?? { rows: [] };
  const num = (rows) => rows.filter((r) => typeof r.pct === "number")
    .map((r) => ({ label: r.label, pct: r.pct, measured: ["live", "ladder"].includes(evidenceClass(r)) }));
  const words = (rows) => rows.filter((r) => typeof r.pct !== "number").map((r) => r.label);
  const thesis = num(sect("zero-trust-thesis").rows);
  const build = num(sect("build-progress").rows);
  const kernel = kernelLedger?.twins ?? [];
  return {
    stages, thesis, build, kernel, assurance,
    meta: {
      caption: `v${version.version} · ${version.packageCount} packages · ${version.testCount} tests · ship-readiness ${pa.shipReadinessPct.toFixed(1)}% · Zero-Trust thesis avg ${pa.ztAvg}% · build avg ${pa.buildAvg}%`,
      provenance: "generated from the closed assurance dependency DAG + component-health + the RD-0528/RD-0361 authority ledgers; exact producer identities are in focused provenance sidecars",
      wordRows: [...words(sect("zero-trust-thesis").rows), ...words(sect("build-progress").rows)],
      // Every registry row, state normalised — the map must not drop a workstream (owner catch: v1 did).
      registry: sect("tracking-registry").rows.map((r) => ({ item: r.item, state: String(r.state) })),
    },
  };
}

function model() {
  const result = deriveRoadmapEvidence(ROOT, {
    repositoryBuildPoint: ROADMAP_BUILD_POINT.stamp.gitCommit,
  });
  if (result.kind === "refused") {
    throw new Error(`roadmap assurance refused: ${result.code}: ${result.detail}`);
  }
  if (result.value.verdictTrit === -1) {
    throw new Error("roadmap assurance denied by at least one exact predecessor");
  }
  const root = result.value.nodes.find((node) => node.id === "roadmap");
  if (root === undefined) throw new Error("roadmap assurance report has no aggregate root");
  const pa = percentAudit();
  const value = buildModel({
    pa,
    hashBaseline: loadJSON(SOURCES.stageHashes),
    ledger: loadJSON(SOURCES.stageLedger),
    kernelLedger: loadJSON(SOURCES.kernelLedger),
    version: loadJSON(SOURCES.version),
    assurance: Object.freeze({
      state: result.value.verdictTrit === 1 ? "CURRENT" : "UNKNOWN",
      rootDigest: root.subjectDigest,
    }),
  });
  return Object.freeze({
    value,
    percentAudit: pa,
    descriptor: loadJSON(DESCRIPTOR_PATH),
  });
}

// One pure classifier for a target's state (R&D 0424, equivalence-proven 4/4 against the inline loop
// before adoption). Extracted so the ABSENCE path is drivable by the self-test — it was the one branch
// proven only by a one-off manual drive, which is not a repeatable proof.
export function classifyTarget(abs, block) {
  if (!existsSync(abs)) return "gone-missing";
  const text = readFileSync(abs, "utf8");
  const expected = injectBlock(text, block);
  if (expected === undefined) return "gone-unmarked";
  return text === expected ? "ok" : "stale";
}

const markerBounds = (text) => {
  const b = text.indexOf(BEGIN);
  const e = text.indexOf(END);
  if (
    b < 0
    || e < b
    || text.indexOf(BEGIN, b + BEGIN.length) >= 0
    || text.indexOf(END, e + END.length) >= 0
  ) return undefined;
  return { b, e };
};
const injectBlock = (text, block) => {
  const bounds = markerBounds(text);
  if (bounds === undefined) return undefined;
  const newline = text.includes("\r\n") ? "\r\n" : "\n";
  const localBlock = block.replace(/\r?\n/g, newline);
  return text.slice(0, bounds.b) + localBlock + text.slice(bounds.e + END.length);
};
const currentBlock = (text) => {
  const bounds = markerBounds(text);
  return bounds === undefined ? undefined : text.slice(bounds.b, bounds.e + END.length);
};

function normalizedTargetTemplate(bytes, label, strict) {
  let text;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch (error) {
    if (!strict) return Buffer.from(bytes);
    throw new Error(`${label} is not canonical UTF-8: ${error.message}`);
  }
  const bounds = markerBounds(text);
  if (bounds === undefined) {
    if (!strict) return Buffer.from(bytes);
    throw new Error(`${label} has missing, duplicated, or misordered roadmap markers`);
  }
  const template = `${text.slice(0, bounds.b)}<!-- ROADMAP:OWNED-REGION -->${text.slice(bounds.e + END.length)}`
    .replaceAll("\r\n", "\n");
  if (template.includes("\r")) {
    if (!strict) return Buffer.from(bytes);
    throw new Error(`${label} contains a bare carriage return`);
  }
  return Buffer.from(template, "utf8");
}

function sameOptionalBytes(left, right) {
  return left === undefined
    ? right === undefined
    : right !== undefined && Buffer.compare(left, right) === 0;
}

function meaningfulTargetChange(commit, path) {
  const current = gitFile(commit, path);
  const currentTemplate = current === undefined
    ? undefined
    : normalizedTargetTemplate(current, `${commit}:${path}`, false);
  const ancestry = git(["rev-list", "--parents", "-n", "1", commit]).trim().split(/\s+/u);
  if (ancestry[0] !== commit || ancestry.some((identity) => !GIT_IDENTITY.test(identity))) {
    throw new Error("Git returned malformed roadmap build-point ancestry");
  }
  const parents = ancestry.slice(1);
  if (parents.length === 0) return currentTemplate !== undefined;
  return !parents.some((parent) => {
    const bytes = gitFile(parent, path);
    const template = bytes === undefined
      ? undefined
      : normalizedTargetTemplate(bytes, `${parent}:${path}`, false);
    return sameOptionalBytes(currentTemplate, template);
  });
}

function currentTargetDiffersFromHead(path) {
  const head = gitFile("HEAD", path);
  if (head === undefined || !existsSync(join(ROOT, ...path.split("/")))) return true;
  const current = readFileSync(join(ROOT, ...path.split("/")));
  return Buffer.compare(
    normalizedTargetTemplate(current, path, true),
    normalizedTargetTemplate(head, `HEAD:${path}`, false),
  ) !== 0;
}

function roadmapBuildPoint() {
  try {
    const dirtyPaths = new Set([
      ...nulPaths(
        git(["diff", "--name-only", "-z", "HEAD", "--"], null),
        "roadmap dirty-path enumeration",
      ),
      ...nulPaths(
        git(["ls-files", "--others", "--exclude-standard", "-z"], null),
        "roadmap untracked-path enumeration",
      ),
    ]);
    const dirty = [...dirtyPaths].filter((path) =>
      relevantOrdinaryPath(path)
      || (TARGETS.includes(path) && currentTargetDiffersFromHead(path))
    ).sort((left, right) => Buffer.compare(Buffer.from(left), Buffer.from(right)));

    const commits = git(["rev-list", "--topo-order", "HEAD"])
      .split(/\r?\n/u)
      .filter((commit) => commit.length > 0);
    if (commits.length === 0 || commits.length > MAX_GIT_COMMITS) {
      throw new Error("Git history exceeds the roadmap provenance bound");
    }
    for (const commit of commits) {
      if (!GIT_IDENTITY.test(commit)) throw new Error("Git returned a malformed roadmap build point");
      const changed = new Set(nulPaths(git([
        "diff-tree",
        "--root",
        "-m",
        "--no-commit-id",
        "--name-only",
        "-r",
        "-z",
        commit,
      ], null), "roadmap build-point path enumeration", false));
      if (
        [...changed].some(relevantOrdinaryPath)
        || [...changed].some((path) => TARGETS.includes(path) && meaningfulTargetChange(commit, path))
      ) {
        const epochText = git(["show", "-s", "--format=%ct", commit]).trim();
        if (!/^\d+$/u.test(epochText)) throw new Error("Git returned a malformed roadmap build timestamp");
        const epoch = Number(epochText);
        if (!Number.isSafeInteger(epoch) || epoch < 0) {
          throw new Error("Git returned an out-of-range roadmap build timestamp");
        }
        return Object.freeze({
          kind: dirty.length === 0 ? "clean" : "dirty",
          dirty: Object.freeze(dirty),
          stamp: Object.freeze({
            schemaVersion: 1,
            tool: TOOL,
            authority: "NONE",
            gitCommit: commit,
            builtAt: new Date(epoch * 1000).toISOString(),
            node: process.version,
          }),
        });
      }
    }
    throw new Error("no commit owns the roadmap provenance inputs");
  } catch (error) {
    return Object.freeze({
      kind: "refused",
      code: "ROADMAP_PROVENANCE_BUILD_POINT",
      detail: error instanceof Error ? error.message : "roadmap provenance derivation failed",
    });
  }
}

function boundedInput(relativePath) {
  const absolute = resolve(ROOT, ...relativePath.split("/"));
  const delta = relative(ROOT, absolute);
  if (delta.startsWith("..") || resolve(absolute) !== absolute) {
    throw new Error(`roadmap authoritative input escapes the repository: ${relativePath}`);
  }
  const stat = lstatSync(absolute);
  if (!stat.isFile() || stat.isSymbolicLink() || stat.size < 1 || stat.size > MAX_INPUT_BYTES) {
    throw new Error(`roadmap authoritative input is not one bounded regular file: ${relativePath}`);
  }
  const actual = realpathSync.native(absolute);
  const actualDelta = relative(ROOT, actual);
  if (actualDelta.startsWith("..")) {
    throw new Error(`roadmap authoritative input resolves outside the repository: ${relativePath}`);
  }
  const bytes = readFileSync(absolute);
  if (bytes.length !== stat.size) throw new Error(`roadmap authoritative input changed: ${relativePath}`);
  return bytes;
}

function u64(value) {
  const bytes = Buffer.alloc(8);
  bytes.writeBigUInt64BE(BigInt(value));
  return bytes;
}

function authoritativeInputsDigest(derived) {
  const descriptor = derived.descriptor;
  if (!Array.isArray(descriptor?.nodes) || descriptor.root === null || typeof descriptor.root !== "object") {
    throw new Error("roadmap dependency descriptor cannot disclose authoritative inputs");
  }
  const paths = new Set([
    DESCRIPTOR_PATH,
    TOOLING_POLICY_PATH,
    ...Object.values(SOURCES),
    ...ROADMAP_SUPPORT_PATHS,
    descriptor.root.toolPath,
  ]);
  for (const node of descriptor.nodes) {
    if (!Array.isArray(node?.artifactPaths)) {
      throw new Error("roadmap dependency node cannot disclose artifact paths");
    }
    for (const path of [...node.artifactPaths, node.provenancePath, node.toolPath]) {
      if (typeof path !== "string") throw new Error("roadmap dependency path is malformed");
      paths.add(path);
    }
  }

  const entries = [];
  let total = 0;
  for (const path of paths) {
    const bytes = boundedInput(path);
    total += bytes.length;
    if (!Number.isSafeInteger(total) || total > MAX_TOTAL_INPUT_BYTES) {
      throw new Error("roadmap authoritative inputs exceed the total byte bound");
    }
    entries.push({
      labelBytes: Buffer.from(`file:${path}`, "utf8"),
      valueBytes: bytes,
      readback: () => boundedInput(path),
    });
  }
  for (const path of TARGETS) {
    const raw = boundedInput(path);
    const bytes = normalizedTargetTemplate(raw, path, true);
    total += raw.length;
    if (!Number.isSafeInteger(total) || total > MAX_TOTAL_INPUT_BYTES) {
      throw new Error("roadmap authoritative inputs exceed the total byte bound");
    }
    entries.push({
      labelBytes: Buffer.from(`target-template:${path}`, "utf8"),
      valueBytes: bytes,
      readback: () => normalizedTargetTemplate(boundedInput(path), path, true),
    });
  }
  const { provenance: _volatilePercentProvenance, ...percentContent } = derived.percentAudit;
  const percentBytes = Buffer.from(JSON.stringify(percentContent), "utf8");
  const modelBytes = Buffer.from(JSON.stringify(derived.value), "utf8");
  total += percentBytes.length + modelBytes.length;
  if (!Number.isSafeInteger(total) || total > MAX_TOTAL_INPUT_BYTES) {
    throw new Error("roadmap authoritative inputs exceed the total byte bound");
  }
  entries.push({
    labelBytes: Buffer.from("virtual:percent-audit-content", "utf8"),
    valueBytes: percentBytes,
  });
  entries.push({
    labelBytes: Buffer.from("virtual:roadmap-model", "utf8"),
    valueBytes: modelBytes,
  });

  for (const entry of entries) {
    if (entry.readback === undefined) continue;
    const again = entry.readback();
    if (Buffer.compare(again, entry.valueBytes) !== 0) {
      throw new Error("roadmap authoritative input changed during readback");
    }
  }
  entries.sort((left, right) => Buffer.compare(left.labelBytes, right.labelBytes));
  const hash = createHash("sha256").update(AUTHORITATIVE_INPUT_DOMAIN);
  for (const entry of entries) {
    hash.update(u64(entry.labelBytes.length));
    hash.update(entry.labelBytes);
    hash.update(u64(entry.valueBytes.length));
    hash.update(entry.valueBytes);
  }
  return hash.digest("hex");
}

const ROADMAP_BUILD_POINT = roadmapBuildPoint();
if (ROADMAP_BUILD_POINT.kind === "refused") {
  throw new Error(`${ROADMAP_BUILD_POINT.code}: ${ROADMAP_BUILD_POINT.detail}`);
}

// --- self-test: DRIVE the guards with synthetic bad inputs, never reason about them ---------------------
if (OPTIONS.mode === "self-test") {
  // Counts are DERIVED, never typed — a tool whose purpose is "stop hand-typing numbers" must not hand-type its own.
  let checks = 0, driven = 0;
  const ok = (c, m) => { checks++; if (m.startsWith("★ DRIVEN")) driven++; console.log(`  ${c ? "✅" : "❌"} ${m}`); if (!c) process.exitCode = 1; };
  const throws = (fn) => { try { fn(); return false; } catch { return true; } };

  const hb = loadJSON(SOURCES.stageHashes), led = loadJSON(SOURCES.stageLedger);
  const stages = stageLine(hb, led);
  ok(stages.length === PIPELINE_ORDER.length, `stage line renders all ${PIPELINE_ORDER.length} stages`);
  ok(stages.some((s) => s.authoritative) && stages.every((s) => s.pinned), "at least one stage is flipped and every stage is byte-pinned (control: a blank ledger would fail this)");

  // DRIVEN control 1: a stage the order list has never heard of must ABORT, not silently vanish.
  ok(throws(() => stageLine({ stages: { ...hb.stages, "brand-new-stage": { sha256: "x" } } }, led)),
    "★ DRIVEN: an unplaced stage ABORTS the map (a new stage cannot be silently dropped)");
  // DRIVEN control 2: an empty baseline is fail-closed, not a zero-station map.
  ok(throws(() => stageLine({ stages: {} }, led)), "★ DRIVEN: an empty stage baseline is fail-closed");
  // DRIVEN control 3: an EMPTY ledger must render zero authoritative — proving fill is read, not assumed.
  ok(stageLine(hb, { twins: [] }).every((s) => !s.authoritative), "★ DRIVEN: an empty authority ledger renders 0 solid stations");

  // DRIVEN control 4: the evidence classifier must actually discriminate — the whole point of the dashed ring.
  ok(evidenceClass({ evidence: { live: "x" } }) === "live", "evidence: live detected");
  ok(evidenceClass({ evidence: { ladder: ["A"] } }) === "ladder", "evidence: ladder detected");
  ok(evidenceClass({ evidence: { asserted: "x" } }) === "asserted", "evidence: asserted detected");
  ok(evidenceClass({ evidence: { ladder: [] } }) === "asserted", "★ DRIVEN: an EMPTY ladder is asserted, not measured (an empty set is not evidence)");

  const m = model().value;
  const block = renderBlock(m), svg = renderSVG(m);
  ok(block.startsWith(BEGIN) && block.trimEnd().endsWith(END), "block is marker-delimited");
  ok(renderBlock(model().value) === block, "generation is DETERMINISTIC (no clock — the gate cannot false-positive)");
  const nonFiniteToken = ["N", "a", "N"].join("");
  ok(svg.startsWith("<svg") && svg.includes("</svg>") && !svg.includes(nonFiniteToken), "SVG is well-formed and free of non-finite coordinates");
  ok(!/\u0000/.test(block + svg), "★ output carries no literal NUL bytes (the defect class shipped twice this session)");
  ok(m.thesis.concat(m.build).some((r) => !r.measured), "★ the asserted class is present and rendered — the map is not flattering itself");
  ok(currentBlock(`x${block.replace(/\d+%/, "999%")}y`) !== block, "drift detector: a hand-edited block differs from the generated one");
  // Build identity is kept in the sidecar rather than embedded as mutable
  // dirty-tree state. Every block byte is therefore subject to drift checking.
  ok(block.replace(/\d+%/, "999%") !== block,
    "★ DRIVEN: a DATA difference changes the exact generated block");
  const crlfDoc = `before\r\n${BEGIN}\r\nstale\r\n${END}\r\nafter\r\n`;
  const crlfExpected = injectBlock(crlfDoc, block);
  ok(crlfExpected !== undefined && crlfExpected.includes("\r\n") && !/(?<!\r)\n/.test(crlfExpected),
    "★ DRIVEN: injection preserves the target's CRLF convention deterministically");
  // ABSENCE PATH, driven (R&D 0424): four classifier outcomes against fixtures built from the REAL
  // README target — so "ok" is a genuine positive, not a straw one. The stale fixture asserts its own
  // validity first (R&D's v1 fixture mutated a % OUTSIDE the block and nearly reported a false miss):
  // a synthetic bad input has to actually be bad.
  {
    const { writeFileSync: wf, rmSync, mkdtempSync } = await import("node:fs");
    const { tmpdir } = await import("node:os");
    const dir = mkdtempSync(join(tmpdir(), "roadmap-absence-"));
    const real = readFileSync(join(ROOT, ...TARGETS[0].split("/")), "utf8");
    const okPath = join(dir, "ok.md"); wf(okPath, real);
    const unmarkedPath = join(dir, "unmarked.md"); wf(unmarkedPath, real.replace(BEGIN, "").replace(END, ""));
    const b = real.indexOf(BEGIN), e = real.indexOf(END) + END.length;
    const staleBody = real.slice(0, b) + real.slice(b, e).replace(/\d+%/, "999%") + real.slice(e);
    ok(currentBlock(staleBody) !== currentBlock(real), "★ fixture validity: the stale mutation changed the BLOCK (not some % outside it)");
    const stalePath = join(dir, "stale.md"); wf(stalePath, staleBody);
    const liveBlock = currentBlock(real); // classify against the doc's own block so "ok" is exact
    ok(classifyTarget(join(dir, "no-such-file.md"), liveBlock) === "gone-missing", "★ DRIVEN: a missing target classifies gone-missing");
    ok(classifyTarget(unmarkedPath, liveBlock) === "gone-unmarked", "★ DRIVEN: stripped markers classify gone-unmarked");
    ok(classifyTarget(stalePath, liveBlock) === "stale", "★ DRIVEN: an in-block data change classifies stale");
    ok(classifyTarget(okPath, liveBlock) === "ok", "★ DRIVEN: the unchanged real doc classifies ok — the non-vacuity leg (a classifier failing everything would pass the other three)");
    rmSync(dir, { recursive: true, force: true });
  }

  // COMPLETENESS (owner catch): every tracking-registry workstream must appear in BOTH outputs — the v1
  // map dropped the whole section and nothing noticed. Checked against the SOURCE count, not a typed one.
  ok(m.meta.registry.length > 0 && m.meta.registry.every((r) => block.includes(`registry (${m.meta.registry.length})`) && svg.includes(esc(r.item))),
    `★ DRIVEN-BY-SOURCE: all ${m.meta.registry.length} registry workstreams render in the SVG and the block counts them`);

  console.log(process.exitCode ? "  roadmap self-test FAILED" : `  roadmap self-test: ${checks} checks incl. ${driven} driven controls ✅`);
  process.exit(process.exitCode ?? 0);
}

export function liveRoadmapSvg() {
  const derived = model();
  return renderSVG(derived.value);
}

const IS_MAIN = process.argv[1] !== undefined
  && process.argv[1].replace(/\\/g, "/").endsWith("scripts/gen-roadmap.mjs");
if (!IS_MAIN) {
  // imported as a library (J8 dirty-tree SVG regen). CLI modes stay behind IS_MAIN.
} else if (
  (OPTIONS.mode === "write" || OPTIONS.mode === "check")
  && ROADMAP_BUILD_POINT.kind === "dirty"
) {
  console.error(
    `roadmap: relevant provenance input is dirty: ${ROADMAP_BUILD_POINT.dirty[0]}`,
  );
  process.exit(1);
}

if (IS_MAIN) {
const derived = model();
const m = derived.value;
const block = renderBlock(m);
const previewHead = OPTIONS.mode === "preview" ? git(["rev-parse", "HEAD"]).trim() : undefined;
if (previewHead !== undefined && !GIT_IDENTITY.test(previewHead)) {
  throw new Error("roadmap preview: Git returned a malformed HEAD");
}
const svg = renderSVG(m, previewHead === undefined ? undefined : {
  head: previewHead,
  dirtyCount: ROADMAP_BUILD_POINT.dirty.length,
});
const authoritativeDigest = authoritativeInputsDigest(derived);
const provenanceText = JSON.stringify(
  {
    ...ROADMAP_BUILD_POINT.stamp,
    authoritativeInputsDigest: authoritativeDigest,
  },
  undefined,
  2,
) + "\n";

/**
 * Derive every living-document output before any mutation.
 */
function deriveTargets() {
  const outputs = new Map();
  const failures = [];
  for (const rel of TARGETS) {
    const abs = join(ROOT, rel);
    if (!existsSync(abs)) {
      failures.push(`${rel} (file MISSING)`);
      continue;
    }
    const next = injectBlock(readFileSync(abs, "utf8"), block);
    if (next === undefined) {
      failures.push(`${rel} (ROADMAP markers missing, duplicated, or misordered)`);
      continue;
    }
    outputs.set(abs, next);
  }
  return { outputs, failures };
}

if (OPTIONS.mode === "check") {
  const { outputs, failures } = deriveTargets();
  const expected = new Map([
    ...outputs,
    [SVG_OUT, svg],
    [PROVENANCE_OUT, provenanceText],
  ]);
  const stale = [...expected.entries()]
    .filter(([path, bytes]) =>
      !existsSync(path)
      || readFileSync(path, "utf8") !== bytes)
    .map(([path]) => relative(ROOT, path).replace(/\\/g, "/"));
  if (failures.length > 0 || stale.length > 0) {
    for (const failure of failures) {
      console.error(`  ❌ roadmap-drift: ${failure}`);
    }
    if (stale.length > 0) {
      console.error(`  ❌ roadmap-drift: missing or stale output(s): ${stale.join(", ")}`);
    }
    console.error("  No files written. Fix with: node scripts/gen-roadmap.mjs --write");
    process.exit(1);
  }
  console.log(`  ✅ roadmap-drift: all ${expected.size} output(s) match the live ledgers.`);
  process.exit(0);
}

if (OPTIONS.mode === "write") {
  const { outputs, failures } = deriveTargets();
  if (failures.length > 0) {
    for (const failure of failures) {
      console.error(`  ❌ roadmap-write: ${failure}`);
    }
    console.error("  Refusing partial generation; no files written.");
    process.exit(1);
  }
  mkdirSync(dirname(SVG_OUT), { recursive: true });
  writeFileSync(SVG_OUT, svg);
  writeFileSync(PROVENANCE_OUT, provenanceText);
  let wrote = 0;
  for (const [path, bytes] of outputs) {
    if (readFileSync(path, "utf8") !== bytes) {
      writeFileSync(path, bytes);
      wrote++;
    }
  }
  console.log(`  roadmap: wrote SVG + provenance and updated ${wrote} doc(s)`);
  process.exit(0);
}

if (OPTIONS.mode === "preview") {
  mkdirSync(dirname(PREVIEW_OUT), { recursive: true });
  const temporary = join(dirname(PREVIEW_OUT), `.roadmap-preview-${randomUUID()}.tmp`);
  let created = false;
  try {
    const fd = openSync(temporary, "wx", 0o600);
    created = true;
    try {
      writeFileSync(fd, svg);
    } finally {
      closeSync(fd);
    }
    // Rename replaces the preview directory entry, not bytes in a pre-existing
    // symlink or hard link. Canonical roadmap files are never output targets.
    renameSync(temporary, PREVIEW_OUT);
  } finally {
    if (created && existsSync(temporary)) unlinkSync(temporary);
  }
  console.log("  roadmap: wrote NON-AUTHORITATIVE preview to build/roadmap/roadmap-preview.svg; canonical outputs untouched");
  process.exit(0);
}

console.log(block);
}
